name: "Hola Mundo CI/CD"

on:
  push:
    branches:
      - "main"

jobs:
  hola_mundo:
    runs-on: ubuntu-20.04
    steps:
      - name: Escribir mensaje
        run: echo "Hola Mundo CI/CD"
      - run: echo "Chaun Mundo"
