name: "Push event"

on:
  push:
    branches:
      - "main"

jobs:
  BuildAndTest:
    runs-on: ubuntu-20.04
    steps:
    - name: Cancelar trabajos previos
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: "Instalar dependencias"
      run: npm ci
    - name: "Correr ESlint"
      run: npm run lint
    - name: "Buildeamos nuestra app"
      run: npm run build
    - name: "Correr Test"
      run: npm run test